.github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md
To Close: #39
Pull request template created
=> Feat: Added Pull Request template

.env.example, package-lock.json, package.json, server.js, src/config/database/connection.js, src/controllers/platformInfoController.js, src/middleware/admin.js, src/middleware/auth.js, src/models/PlatformInfo.js, src/models/User.js, src/routes/admin.js, src/routes/platformInfo.js, src/validators/platformInfoValidator.js
Implement a robust platform information management system to allow administrators to create, update, retrieve, and delete essential platform information such as About ChainVerse Academy, Privacy Policy, Terms & Conditions, and Community Guidelines.
closes #38 
1. Install dependencies: `npm install`
2. Set up `.env` file with required configurations
3. Start the server: `npm run dev`
4. Use Postman or similar tool to test endpoints
- Ensure MongoDB is running locally or update connection string
- Use provided Postman collection for endpoint testing
- Review authentication and authorization mechanisms
=> Platform Information Management System PR

package-lock.json, package.json, server.js, src/controllers/studyGroupController.js, src/middlewares/auth.js, src/middlewares/fileUpload.js, src/models/course.js, src/models/studyGroup.js, src/models/studyGroupDiscussion.js, src/models/studyGroupFile.js, src/models/studyGroupMember.js, src/routes/studyGroupRoutes.js, src/utils/fileStorage.js, src/utils/notifications.js, src/utils/rateLimit.js
This PR implements the study group feature for ChainVerse Academy, enabling students to create and join study groups for their enrolled courses. The feature includes functionality for creating study groups, joining groups, managing discussions, file sharing, and sending notifications for key events. 
Closes: #30  
- Course enrollment verification
- Private/public group access controls
- Rate limiting for discussions
- File upload validation and security
- npm run dev to start the saver
- try any of the endpoint (http://localhost:3000/)
=>  Implemented Study Groups & Collaboration Feature in ChainVerse Academy

package-lock.json, package.json, src/config/database/passport.js, src/controllers/authController.js, src/models/student.js
models/student.js:
Added googleId field (String, unique, sparse) to studentSchema.
config/passport.js:
Created new file for Passport.js configuration.
Added GoogleStrategy with clientID, clientSecret, and callbackURL.
Implemented user creation/update and serialization/deserialization.
controllers/authController.js:
Imported passport.
Added exports.googleAuth for OAuth initiation.
Added exports.googleCallback for token generation and cookie setting.
Kept existing methods unchanged.
server.js:
Imported session and passport.
Added session and passport middleware.
Added routes: /student/register/google-auth, /student/login/google-auth, /student/google-auth/callback.
fixed: Implement Google OAuth for Student Signup and Login #5 
- [ ✔] My code follows the project's coding style.  
- [✔ ] I …
=> feat: Implement Google OAuth for Student Signup and Login

src/controllers/organizationController.js, src/models/organization.js, src/routes/index.js, src/routes/organization.js
This PR implements the routes and the relevant controller logic for the organization subscription management feature. This allows organizations to subscribe to plans and monitor members according to the limits of the plan.
Closes #37 
- Added `src/routes/organization.js` to declare routes for the feature.
- Modified `src/routes/index.js` to include the organization routes.
- Added `src/controllers/organizationController.js` to implement logic for handling organization route calls.
- Added `src/models/organization.js` to declare the schema for the organization model.
=> [WIP] Organization Subscription Management implementation

config.env, server.js, src/config/database/connection.js, src/controllers/removalRequestController.js, src/middlewares/adminAuthorization.js, src/middlewares/auth.js, src/models/requestRemoval.js, src/routes/accountRemovalRoute.js
Implemented an API that allows users to request the deactivation or permanent deletion of their account. The API should also allow admins to review and process these requests.
closes #74
=> Implemented Account Deactivation/Deletion Request API

server.js, src/controllers/courseController.js, src/controllers/financialAidController.js, src/middlewares/auth.js, src/middlewares/authMiddleware.js, src/models/financialAid.js, src/routes/courseRoute.js, src/routes/financialAidRoute.js, src/tests/unit/financialAid.test.js
This PR implements a new feature for ChainVerse Academy that allows students to apply for financial aid. The feature provides endpoints for submitting applications and tracking application status, ensuring financially constrained students can access learning opportunities while maintaining transparency in the aid process.
Closes #54
1. Clone the branch and install dependencies:
```bash
npm install
```
2. Start the development server:
```bash
npm run dev
```
3. Use Postman to test the following scenarios:
```http
POST /api/financial-aid/apply
Headers:
x-auth-token: <jwt-token>
Body:
{
"courseId": "<valid-course-id>",
"reason": "I am currently a student working part-time and cannot afford the full price of this course. I believe this course will significantly improve my employment prospects …
```
=> PR for Implement Financial Aid Application Feature for Students

.env.example, package-lock.json, package.json, server.js, src/controllers/Auth2FAController.js, src/models/User.js, src/routes/2factorRoute.js
Description
This PR implements Two-Factor Authentication (2FA) for ChainVerse users using the Google Authenticator app.
Users can enable, verify, and disable 2FA securely through API endpoints.
Related Issues
Closes #72 
Changes Made
Added enable2FA, verify2FA, and disable2FA controller functions in Auth2FAController.js.
Created 2FA API routes in Auth2FARoutes.js.
Secured all 2FA routes using authentication middleware (auth).
Used speakeasy and qrcode libraries for generating and verifying 2FA codes.
Password validation added when disabling 2FA using bcryptjs.
How to Test
Enable 2FA
Send a POST request to /auth/2fa/enable (authenticated).
A QR code URL and manual entry key will be returned.
Scan the QR code using Google Authenticator.
Verify 2FA
Send a POST request to /auth/2fa/verify …
=> implemented 2FA authentication

server.js, src/controllers/faqController.js, src/models/faq.js, src/routes/faqRoute.js, src/validators/faqValidator.js
This PR implements the FAQ Management API with full CRUD functionality as specified in issue #67. The implementation includes:
- Create, Read, Update, Delete FAQ endpoints
- Admin-only access for write operations
- Comprehensive input validation
- Proper error handling and responses
Fixes #67
1. Start the server: `node server.js`  
2. Test endpoints using Postman:  
**Public Routes (GET):**  
- `GET /faqs` - List all FAQs  
- `GET /faqs/:id` - Get single FAQ  
**Admin Routes (require auth token):**  
- `POST /faqs` - Create new FAQ  
- `PATCH /faqs/:id` - Update FAQ  
- `DELETE /faqs/:id` - Delete FAQ  
Test cases to verify:  
- All endpoints return proper status codes  
- Validation rejects invalid inputs  
- Non-admin users cannot modify FAQs  
- Error handling works for missing …
=> Implement FAQ Management API

package-lock.json, package.json, src/controllers/certificateController.js, src/models/Certificate.js, src/routes/certificateRoutes.js, src/routes/index.js, src/tests/integration/certificateRoutes.test.js, src/tests/unit/certificate.test.js
The Student Certificate Retrieval & Download on Dashboard #59 has been successfully created and implemented, ensuring it  includes both single certificate downloads and bulk downloads (as a ZIP file), along with proper security measures. also the following features as stated below was achieved
Retrieval of all certificates belonging to the authenticated student.
Supported all optional filters such as courseId or completionDate.
Returns an array of certificate metadata including download links.
2.The retrieval of a Single Certificate
Endpoint: GET /certificates/:certificateId
which returns metadata and a download link for a specific certificate.
Verifies the certificate ownership to ensure the student can access it.
3. Downloaded Options
Bulk Download:
Endpoint: GET …
=>  Student Certificate Retrieval & Download dashboard

server.js, src/controllers/reportAbuseController.js, src/models/reportAbuse.js, src/routes/index.js, src/routes/reportAbuseRoute.js
This PR implements the Report Abuse/Flag Content feature, enabling users to report inappropriate content and admins to manage these reports. The implementation includes:
- New ReportAbuse model and database schema
- API endpoints for submitting, retrieving, and updating reports
- Rate limiting
Closes #71 
- Added Report Mongoose model with required fields
- Implemented three main endpoints:
- POST /reports/abuse - Submit new reports
- GET /reports/abuse - Retrieve reports (admin only)
- PATCH /reports/abuse/:reportId - Update report status (admin only)
- Implemented rate limiting (5 reports per 60 minutes per user)
=> Implement Report Abuse/Flag Content API

API_DOCS.md, package-lock.json, package.json, src/controllers/tutorReportController.js, src/models/loginsLog.js, src/routes/tutorReportRoutes.js
Implements a comprehensive performance reporting system for tutors on chainVerse academy. This system enables tutors to track course performance, view rankings, and access detailed analytics through various endpoints.
Closes #24 
- GET /tutor/reports/courses
- GET /tutor/reports/courses/:id (with CSV export)
- Course leaderboard by various metrics
- Tutor rankings with Hall of Fame
- Redis caching for performance
- Rate limiting (100 requests/15min)
- MongoDB aggregation pipelines
1. Install new dependencies:
```bash
npm install express-rate-limit json2csv
Start the server:
node server.js
Test endpoints (using Postman or curl):
GET /tutor/reports/courses?interval=monthly
GET /tutor/reports/courses/[course_id]?format=csv
GET /tutor/reports/leaderboard?metric=purchases
GET …
```
=> feat: implement tutor performance reporting system

src/controllers/ShareAnalytics.js, src/controllers/certificateController.js, src/middlewares/auth.js, src/models/Certificate.js, src/routes/certificateRoutes.js, src/tests/controllers/certificateController.test.js, src/utils/certificateGenerator.js, src/utils/cloudStorage.js, src/utils/hashGenerator.js, src/utils/logger.js
on This PR , i  implements the social sharing and public link generation features for certificates, enabling students to share their achievements on social media platforms. It includes new endpoints, improved error handling, and integration with cloud storage for certificate images.
closes #60 
1. GET /certificates/:certificateId/public-link: Generates a public link for certificates.
2. GET /certificates/:certificateId/share-metadata: Provides metadata for social sharing.
3. POST /certificates/:certificateId/track-share: Tracks sharing events for analytics.
4. GET /certificates/public/:publicHash: Retrieves public certificate details.
5. Integrated cloud storage for secure certificate image URLs.
6. Refactored repetitive logic for public hash and image URL generation.
7. Improved error …
=> feat: Add social sharing and public link generation for certificates

server.js, src/controllers/careerController.js, src/models/careers.js, src/routes/careerRoutes.js, src/services/careerService.js, src/utils/slugify.js
Closes #91
📚 Overview
This PR implements a full-featured REST API to manage career tracks and opportunities within ChainVerse Academy. It enables admins to manage career paths while exposing public endpoints for general users to explore them.
🔧 Endpoints & Features
Admin-only Endpoints:
Create Career Track
POST /careers
Fields:
title (String)
slug (String, optional — auto-generated if not provided)
description (Text/HTML)
image (File or URL, optional)
requirements[] (Array of Strings)
outcomes[] (Array of Strings)
Update Career Track
PATCH /careers/:id
Delete Career Track
DELETE /careers/:id
Public Endpoints:
Get All Career Tracks
GET /careers
Get Career Track by ID
GET /careers/:id
🔐 Access Control
Admin Only: Endpoints for creating, updating, and deleting use JWT and roleMiddleware to …
=>  Career Management API for ChainVerse Academy Implemented

src/middlewares/auth.js, src/models/Certificate.js, src/models/course.js, src/models/student.js, src/models/studyGroup.js, src/routes/studentReports.js, src/tests/integration/studentReports.test.js, src/utils/tokenHelper.js
This PR implements the feature to generate individual and batch student reports, providing insights into student learning activity across courses. The reports include key metrics such as enrolled courses, completed courses, certificates earned, and more.
closes #62 
```
Setup Environment:
Run Tests:
Manual Testing:
```
=> Implemented Student Reports & Analytics Feature

src/controllers/courseRatingController.js, src/models/courseRating.js, src/routes/courseRatingRoutes.js, src/validators/ratingValidator.js
**Description**
This PR introduces a comprehensive Course Ratings & Feedback system for ChainVerse Academy. The implementation allows students to rate courses, provide optional feedback, and suggest improvements. The system ensures proper validation, role-based access control, and dynamically updates course average ratings.
**Related Issues**
Closes #16  - Implement Course Ratings & Feedback feature
**Changes Made**
- Created new CourseRating model with validation for ratings (1-5)
- Implemented five new API endpoints for rating management:
- POST /courses/:id/rate - Submit a new rating
- GET /courses/:id/ratings - Get all ratings for a course
- GET /courses/:id/my-rating - Get authenticated student's rating
- PUT /courses/:id/rate - Update existing rating
- DELETE /courses/:id/rate - …
=> Course Ratings & Feedback implementation with dynamic rating updates

src/controllers/reportController.js, src/models/certificate.js, src/models/material.js, src/routes/reportRoutes.js, src/tests/unit/report.test.js
=> feature:Tutor Reports & Analytics Reporting Feature #63

.env.example, .gitignore, app.js, src/controllers/guestCartController.js, src/models/guestCart.js, src/routes/guestCartRoute.js, src/tests/integration/guestCart.test.js
Implemented a Guest Cart API to allow unauthenticated users to manage a shopping cart. The feature includes endpoints to create a guest cart, retrieve cart details with populated course information, add courses, update cart items, and remove items from the guest cart.
Closes #102
- Added createGuestCart endpoint to generate a new guest cart with a unique cartKey.
- Implemented getGuestCart endpoint to fetch guest cart details including course title and description via Mongoose population.
- Created addCourseToGuestCart endpoint to add courses or increment quantities if already in cart.
- Developed updateGuestCart endpoint for batch updating cart item quantities or adding new items.
- Built removeItemFromCart endpoint to remove specific course items from the guest cart.
- Added error …
=> Feature: Implement Guest Cart Functionality

src/controllers/courseUpdateController.js, src/models/courseUpdate.js, src/routes/courseUpdateRoutes.js, src/routes/index.js, src/validators/courseUpdateValidator.js
This PR implements a course update system that enables tutors to post updates (announcements, new materials, changes, etc.) for their published courses. Enrolled students receive email notifications when new updates are posted.
1. Created new model `CourseUpdate` to store course updates with fields:
- courseId (reference to Course)
- title
- message
- attachments (optional array)
- createdAt
2. Added new endpoints:
- `POST /tutor/course/:id/update`: For tutors to post course updates
- `GET /student/course/:id/updates`: For enrolled students to retrieve course updates
3. Implemented input validation using express-validator for:
- Title (required, 3-100 characters)
- Message (required, 3-1000 characters)
- Attachments (optional array of strings)
4. Added security features:
- Course …
=> feat: implement course update system for tutors

app.js, src/controllers/cart.controller.js, src/middlewares/authMiddleware.js, src/models/cartItem.js, src/models/product.js, src/routes/cartRoutes.ts, src/services/cartService.js
This PR implements backend logic to merge a guest cart into an authenticated user’s cart upon login. It ensures a seamless shopping experience by combining temporary guest items with the user's persisted cart data.
---
closes #112 
✅ Validate guest cart structure and data types.
✅ Verify product existence and variation validity.
✅ Check for stock availability before merging.
✅ Secure the endpoint using authMiddleware.
✅ Graceful error handling for unauthorized, invalid, or expired tokens.
✅ Optional: Log cart merge events for tracking/debugging.
Add items to a guest cart (e.g., store in localStorage).
Log in to obtain a Bearer token.
Call POST /api/cart/merge with the guest cart in the payload and authorization header.
Use GET /api/cart to confirm:
=>  Merge Guest Cart into Authenticated User Cart

app.js, package-lock.json, package.json, src/controllers/careerController.js, src/controllers/guestCartController.js, src/controllers/privacyPolicyController.js, src/controllers/quizController.js, src/docs/quiz.md, src/middlewares/validation.js, src/models/Quiz.js, src/routes/privacyPolicyRoutes.js, src/routes/quizRoute.js, src/seeds/quizSeeder.js
This PR implements a robust and secure Quiz CRUD API for the chainVerse-backend, covering all requirements from [Issue #105](https://github.com/Gen-x-academy/chainVerse-backend/issues/105):
#105 
- All endpoints tested for valid/invalid input, RBAC, and error handling.
- Quiz CRUD operations verified in MongoDB.
=> Implement Comprehensive Quiz CRUD API for Courses & Lessons

src/controllers/courseReportController.js, src/middlewares/auth.js, src/models/activityLog.js, src/models/courseReport.js, src/routes/courseReportRoutes.js
**Description**
Implements a comprehensive course-level reporting system with real-time metrics tracking, secure API endpoints, and optimized data management.
**Related Issues**
Closes #61  - Course-level reporting feature implementation
**Changes Made**
**How to Test**
1. Start the server:
```bash
npm run dev
```
2. Test admin/staff access:
```bash
curl -X GET "http://localhost:3000/api/reports/courses" -H "Authorization: Bearer YOUR_TOKEN"
```
3. Test single course report:
```bash
curl -X GET "http://localhost:3000/api/reports/course/COURSE_ID" -H "Authorization: Bearer YOUR_TOKEN"
```
4. Verify metrics update:
- Create a new course enrollment
- Check that course report metrics update accordingly
- Verify engagement metrics are calculated correctly
**Checklist**
=> Implement Course Reports & Analytics Feature
